In [24]:
import numpy as np

array = np.arange(1, 101).reshape(10,10) #a matrix from 1-100
print("These are the perfect squares from 1 to 100^2:")
X = pow(array,2) #square of the matrix
print(array)

div_3 = X[X%3==0] #list of all divisible by 3

np.save("div_by_3.npy", div_3)

print("\nThe numbers divisible by 3 amongst the perfect squares are:")
np.load("div_by_3.npy")

These are the perfect squares from 1 to 100^2:
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

The numbers divisible by 3 amongst the perfect squares are:


array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])

In [22]:
import numpy as np

print("The random matrix we got is:")
X = np.random.random((5,5)) #random matrix
print(X)

#Since Z=(X-u)/SD
u = X.mean() #mean
SD = np.std(X) #standard deviation

print("\nThe normalized matrix:")
X_normalize = (X-u)/SD #normalized matrix

np.save("X_normalized.npy", X_normalize)
np.load("X_normalized.npy")

The random matrix we got is:
[[0.00100775 0.41979214 0.0604306  0.49237928 0.09166373]
 [0.75343905 0.56287945 0.27533765 0.46775839 0.55665284]
 [0.96416043 0.46312744 0.75535352 0.50526821 0.83573865]
 [0.85415169 0.56114915 0.61891658 0.11490497 0.99161977]
 [0.34113638 0.93686007 0.36803513 0.87666027 0.23481609]]

The normalized matrix:


array([[-1.80599962, -0.36020932, -1.60085115, -0.10961312, -1.49302343],
       [ 0.79165658,  0.13377814, -0.85891678, -0.19461304,  0.1122817 ],
       [ 1.51914055, -0.21060069,  0.79826602, -0.065116  ,  1.07578362],
       [ 1.13935189,  0.12780456,  0.32723796, -1.41278657,  1.61393979],
       [-0.63175654,  1.42489014, -0.53889265,  1.21705936, -0.99881141]])