In [1]:
import numpy as np

print("The random matrix we got is:")
X = np.random.random((5,5)) #random matrix
print(X)

#Since Z=(X-u)/SD
u = X.mean() #mean
SD = np.std(X) #standard deviation

print("\nThe normalized matrix:")
X_normalize = (X-u)/SD #normalized matrix

np.save("X_normalized.npy", X_normalize)
np.load("X_normalized.npy")

The random matrix we got is:
[[0.72759219 0.09346696 0.68973777 0.12753943 0.10598246]
 [0.53236823 0.13877657 0.48339348 0.89698267 0.06099657]
 [0.61071509 0.40856389 0.97808966 0.30003065 0.19786854]
 [0.53688367 0.54761253 0.3318946  0.59245152 0.43213902]
 [0.60173442 0.02379713 0.49998561 0.71348627 0.33751456]]

The normalized matrix:


array([[ 1.11740498, -1.3360401 ,  0.97094536, -1.20421294, -1.28761736],
       [ 0.36207899, -1.16073618,  0.17259457,  1.77278067, -1.46166878],
       [ 0.66520479, -0.11692286,  2.08658547, -0.53684044, -0.93210801],
       [ 0.37954933,  0.42105956, -0.4135581 ,  0.59454264, -0.02571013],
       [ 0.63045837, -1.60559428,  0.2367899 ,  1.06282888, -0.39181432]])